from .menu import menu_buttons
from .auth import auth_buttons
from .digital_docs import digital_docs_buttons
from .services import services_buttons
from .diia_signature import diia_signature_buttons
from .e_repair import e_repair_buttons
from .lamps_exchange import lamps_exchange_buttons
from .diia_partners import diia_partners_buttons
from .where_diia_accepted import where_diia_accepted_buttons
from .notifications import notifications_buttons
from .my_profile import my_profile_buttons